springdoc:
  swagger-ui:
    enabled: true
    path: "/swagger-ui.html"
  api-docs:
    enabled: true
    path: "/docs"

auth0:
  audience: https://snippet-manager

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-rwvojcsa8mzfij2d.us.auth0.com/



redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  stream:
    request_lint_key: ${REDIS_STREAM_REQUEST_LINT_KEY}
    result_lint_key: ${REDIS_STREAM_RESULT_LINT_KEY}
  groups:
    lint: ${REDIS_STREAM_GROUP_LINT}
