springdoc:
  swagger-ui:
    enabled: true
    path: "/swagger-ui.html"
  api-docs:
    enabled: true
    path: "/docs"

auth0:
  audience: https://snippet-manager

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-rwvojcsa8mzfij2d.us.auth0.com/



redis:
  stream:
    request_lint_key: ${REDIS_STREAM_REQUEST_LINT_KEY}
    result_lint_key: ${REDIS_STREAM_RESULT_LINT_KEY}
  groups:
    lint: ${REDIS_STREAM_GROUP_LINT}

asset:
  service:
    url:
      {$AZURITE_BUCKET_URL_V1:http://localhost:8081/v1/asset/snippet}
