springdoc:
  swagger-ui:
    enabled: true
    path: "/swagger-ui.html"
  api-docs:
    enabled: true
    path: "/docs"

auth0:
  audience: https://snippet-manager

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-rwvojcsa8mzfij2d.us.auth0.com/

