name: "Continuous Deployment to dev"
on:
  push:
    branches:
      - dev
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Create Short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 8

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/ingsis-group-4/snippet-runner-dev:${{ steps.short-sha.outputs.sha }}
            ghcr.io/ingsis-group-4/snippet-runner-dev:latest
          
          build-args: |
            ACTOR=${{ github.repository_owner }}
            TOKEN=${{ secrets.GITHUB_TOKEN }}
      - name: Update server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_URL }}
          username: "snippet-searcher-admin"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd snippet-infra
            docker compose -f docker-compose.dev.yml stop snippet-runner
            docker compose -f docker-compose.dev.yml pull snippet-runner
            docker compose -f docker-compose.dev.yml up snippet-runner -d --build
